name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run convex:codegen
      - run: bun run type-check
      - run: bun run lint
      - run: bun test
      - run: bun run build
        env:
          CONVEX_DEPLOYMENT: ${{ vars.CONVEX_DEPLOYMENT }}
          NEXT_PUBLIC_CONVEX_URL: ${{ vars.NEXT_PUBLIC_CONVEX_URL }}
      - run: bun run start &
      - uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ vars.NEXT_PUBLIC_CONVEX_URL }}
        with:
          install: false
          wait-on: 'http://localhost:6603'
